// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: discovery.proto

package discovery

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerDiscoveryService_QueryWorkerStatus_FullMethodName = "/discovery.WorkerDiscoveryService/QueryWorkerStatus"
)

// WorkerDiscoveryServiceClient is the client API for WorkerDiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerDiscoveryServiceClient interface {
	QueryWorkerStatus(ctx context.Context, in *QueryWorkerStatusRequest, opts ...grpc.CallOption) (*QueryWorkerStatusResponse, error)
}

type workerDiscoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerDiscoveryServiceClient(cc grpc.ClientConnInterface) WorkerDiscoveryServiceClient {
	return &workerDiscoveryServiceClient{cc}
}

func (c *workerDiscoveryServiceClient) QueryWorkerStatus(ctx context.Context, in *QueryWorkerStatusRequest, opts ...grpc.CallOption) (*QueryWorkerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryWorkerStatusResponse)
	err := c.cc.Invoke(ctx, WorkerDiscoveryService_QueryWorkerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerDiscoveryServiceServer is the server API for WorkerDiscoveryService service.
// All implementations must embed UnimplementedWorkerDiscoveryServiceServer
// for forward compatibility.
type WorkerDiscoveryServiceServer interface {
	QueryWorkerStatus(context.Context, *QueryWorkerStatusRequest) (*QueryWorkerStatusResponse, error)
	mustEmbedUnimplementedWorkerDiscoveryServiceServer()
}

// UnimplementedWorkerDiscoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerDiscoveryServiceServer struct{}

func (UnimplementedWorkerDiscoveryServiceServer) QueryWorkerStatus(context.Context, *QueryWorkerStatusRequest) (*QueryWorkerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryWorkerStatus not implemented")
}
func (UnimplementedWorkerDiscoveryServiceServer) mustEmbedUnimplementedWorkerDiscoveryServiceServer() {
}
func (UnimplementedWorkerDiscoveryServiceServer) testEmbeddedByValue() {}

// UnsafeWorkerDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerDiscoveryServiceServer will
// result in compilation errors.
type UnsafeWorkerDiscoveryServiceServer interface {
	mustEmbedUnimplementedWorkerDiscoveryServiceServer()
}

func RegisterWorkerDiscoveryServiceServer(s grpc.ServiceRegistrar, srv WorkerDiscoveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkerDiscoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerDiscoveryService_ServiceDesc, srv)
}

func _WorkerDiscoveryService_QueryWorkerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWorkerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerDiscoveryServiceServer).QueryWorkerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerDiscoveryService_QueryWorkerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerDiscoveryServiceServer).QueryWorkerStatus(ctx, req.(*QueryWorkerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerDiscoveryService_ServiceDesc is the grpc.ServiceDesc for WorkerDiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerDiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discovery.WorkerDiscoveryService",
	HandlerType: (*WorkerDiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryWorkerStatus",
			Handler:    _WorkerDiscoveryService_QueryWorkerStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discovery.proto",
}
