// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: discovery.proto

package discovery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum to describe the current rendering status of a worker.
type WorkerStatus int32

const (
	WorkerStatus_WORKER_STATUS_UNSPECIFIED WorkerStatus = 0 // Default zero value, should not be used
	WorkerStatus_FREE                      WorkerStatus = 1 // Worker is idle and available for tasks
	WorkerStatus_ALLOCATED                 WorkerStatus = 2 // Worker is allocated to a task
	WorkerStatus_BUSY_RENDER_SETUP         WorkerStatus = 3 // Worker is busy with render setup
	WorkerStatus_BUSY_RENDERING            WorkerStatus = 4 // Worker is currently rendering a task
	WorkerStatus_BUSY_OTHER                WorkerStatus = 5 // Worker is busy with non-rendering tasks (e.g., texture streaming)
	WorkerStatus_OFFLINE                   WorkerStatus = 6 // Worker is not responding (this state would be inferred by the leader)
)

// Enum value maps for WorkerStatus.
var (
	WorkerStatus_name = map[int32]string{
		0: "WORKER_STATUS_UNSPECIFIED",
		1: "FREE",
		2: "ALLOCATED",
		3: "BUSY_RENDER_SETUP",
		4: "BUSY_RENDERING",
		5: "BUSY_OTHER",
		6: "OFFLINE",
	}
	WorkerStatus_value = map[string]int32{
		"WORKER_STATUS_UNSPECIFIED": 0,
		"FREE":                      1,
		"ALLOCATED":                 2,
		"BUSY_RENDER_SETUP":         3,
		"BUSY_RENDERING":            4,
		"BUSY_OTHER":                5,
		"OFFLINE":                   6,
	}
)

func (x WorkerStatus) Enum() *WorkerStatus {
	p := new(WorkerStatus)
	*p = x
	return p
}

func (x WorkerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_discovery_proto_enumTypes[0].Descriptor()
}

func (WorkerStatus) Type() protoreflect.EnumType {
	return &file_discovery_proto_enumTypes[0]
}

func (x WorkerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerStatus.Descriptor instead.
func (WorkerStatus) EnumDescriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{0}
}

type Endianness int32

const (
	Endianness_UNKNOWN_ENDIAN Endianness = 0 // Default zero value
	Endianness_LITTLE_ENDIAN  Endianness = 1
	Endianness_BIG_ENDIAN     Endianness = 2
)

// Enum value maps for Endianness.
var (
	Endianness_name = map[int32]string{
		0: "UNKNOWN_ENDIAN",
		1: "LITTLE_ENDIAN",
		2: "BIG_ENDIAN",
	}
	Endianness_value = map[string]int32{
		"UNKNOWN_ENDIAN": 0,
		"LITTLE_ENDIAN":  1,
		"BIG_ENDIAN":     2,
	}
)

func (x Endianness) Enum() *Endianness {
	p := new(Endianness)
	*p = x
	return p
}

func (x Endianness) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Endianness) Descriptor() protoreflect.EnumDescriptor {
	return file_discovery_proto_enumTypes[1].Descriptor()
}

func (Endianness) Type() protoreflect.EnumType {
	return &file_discovery_proto_enumTypes[1]
}

func (x Endianness) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Endianness.Descriptor instead.
func (Endianness) EnumDescriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{1}
}

type QueryWorkerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWorkerStatusRequest) Reset() {
	*x = QueryWorkerStatusRequest{}
	mi := &file_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWorkerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWorkerStatusRequest) ProtoMessage() {}

func (x *QueryWorkerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWorkerStatusRequest.ProtoReflect.Descriptor instead.
func (*QueryWorkerStatusRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{0}
}

type QueryWorkerStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeName         string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`                            // Name of the worker node (e.g., hostname)
	AvailableCores   uint32                 `protobuf:"varint,2,opt,name=available_cores,json=availableCores,proto3" json:"available_cores,omitempty"`         // Number of CPU cores available to the worker
	TotalMemoryBytes uint64                 `protobuf:"varint,3,opt,name=total_memory_bytes,json=totalMemoryBytes,proto3" json:"total_memory_bytes,omitempty"` // Total physical memory in bytes
	FreeMemoryBytes  uint64                 `protobuf:"varint,4,opt,name=free_memory_bytes,json=freeMemoryBytes,proto3" json:"free_memory_bytes,omitempty"`    // Available physical memory in bytes
	Status           WorkerStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=discovery.WorkerStatus" json:"status,omitempty"`                   // Current status of the worker (e.g., FREE, BUSY_RENDERING)
	Endianness       Endianness             `protobuf:"varint,6,opt,name=endianness,proto3,enum=discovery.Endianness" json:"endianness,omitempty"`             // Endianness of the worker's CPU
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryWorkerStatusResponse) Reset() {
	*x = QueryWorkerStatusResponse{}
	mi := &file_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWorkerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWorkerStatusResponse) ProtoMessage() {}

func (x *QueryWorkerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWorkerStatusResponse.ProtoReflect.Descriptor instead.
func (*QueryWorkerStatusResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *QueryWorkerStatusResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *QueryWorkerStatusResponse) GetAvailableCores() uint32 {
	if x != nil {
		return x.AvailableCores
	}
	return 0
}

func (x *QueryWorkerStatusResponse) GetTotalMemoryBytes() uint64 {
	if x != nil {
		return x.TotalMemoryBytes
	}
	return 0
}

func (x *QueryWorkerStatusResponse) GetFreeMemoryBytes() uint64 {
	if x != nil {
		return x.FreeMemoryBytes
	}
	return 0
}

func (x *QueryWorkerStatusResponse) GetStatus() WorkerStatus {
	if x != nil {
		return x.Status
	}
	return WorkerStatus_WORKER_STATUS_UNSPECIFIED
}

func (x *QueryWorkerStatusResponse) GetEndianness() Endianness {
	if x != nil {
		return x.Endianness
	}
	return Endianness_UNKNOWN_ENDIAN
}

var File_discovery_proto protoreflect.FileDescriptor

const file_discovery_proto_rawDesc = "" +
	"\n" +
	"\x0fdiscovery.proto\x12\tdiscovery\"\x1a\n" +
	"\x18QueryWorkerStatusRequest\"\xa3\x02\n" +
	"\x19QueryWorkerStatusResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12'\n" +
	"\x0favailable_cores\x18\x02 \x01(\rR\x0eavailableCores\x12,\n" +
	"\x12total_memory_bytes\x18\x03 \x01(\x04R\x10totalMemoryBytes\x12*\n" +
	"\x11free_memory_bytes\x18\x04 \x01(\x04R\x0ffreeMemoryBytes\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.discovery.WorkerStatusR\x06status\x125\n" +
	"\n" +
	"endianness\x18\x06 \x01(\x0e2\x15.discovery.EndiannessR\n" +
	"endianness*\x8e\x01\n" +
	"\fWorkerStatus\x12\x1d\n" +
	"\x19WORKER_STATUS_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04FREE\x10\x01\x12\r\n" +
	"\tALLOCATED\x10\x02\x12\x15\n" +
	"\x11BUSY_RENDER_SETUP\x10\x03\x12\x12\n" +
	"\x0eBUSY_RENDERING\x10\x04\x12\x0e\n" +
	"\n" +
	"BUSY_OTHER\x10\x05\x12\v\n" +
	"\aOFFLINE\x10\x06*C\n" +
	"\n" +
	"Endianness\x12\x12\n" +
	"\x0eUNKNOWN_ENDIAN\x10\x00\x12\x11\n" +
	"\rLITTLE_ENDIAN\x10\x01\x12\x0e\n" +
	"\n" +
	"BIG_ENDIAN\x10\x022x\n" +
	"\x16WorkerDiscoveryService\x12^\n" +
	"\x11QueryWorkerStatus\x12#.discovery.QueryWorkerStatusRequest\x1a$.discovery.QueryWorkerStatusResponseB>Z<github.com/flynn-nrg/izpi/internal/proto/discovery;discoveryb\x06proto3"

var (
	file_discovery_proto_rawDescOnce sync.Once
	file_discovery_proto_rawDescData []byte
)

func file_discovery_proto_rawDescGZIP() []byte {
	file_discovery_proto_rawDescOnce.Do(func() {
		file_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)))
	})
	return file_discovery_proto_rawDescData
}

var file_discovery_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_discovery_proto_goTypes = []any{
	(WorkerStatus)(0),                 // 0: discovery.WorkerStatus
	(Endianness)(0),                   // 1: discovery.Endianness
	(*QueryWorkerStatusRequest)(nil),  // 2: discovery.QueryWorkerStatusRequest
	(*QueryWorkerStatusResponse)(nil), // 3: discovery.QueryWorkerStatusResponse
}
var file_discovery_proto_depIdxs = []int32{
	0, // 0: discovery.QueryWorkerStatusResponse.status:type_name -> discovery.WorkerStatus
	1, // 1: discovery.QueryWorkerStatusResponse.endianness:type_name -> discovery.Endianness
	2, // 2: discovery.WorkerDiscoveryService.QueryWorkerStatus:input_type -> discovery.QueryWorkerStatusRequest
	3, // 3: discovery.WorkerDiscoveryService.QueryWorkerStatus:output_type -> discovery.QueryWorkerStatusResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_discovery_proto_init() }
func file_discovery_proto_init() {
	if File_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discovery_proto_goTypes,
		DependencyIndexes: file_discovery_proto_depIdxs,
		EnumInfos:         file_discovery_proto_enumTypes,
		MessageInfos:      file_discovery_proto_msgTypes,
	}.Build()
	File_discovery_proto = out.File
	file_discovery_proto_goTypes = nil
	file_discovery_proto_depIdxs = nil
}
