// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: discovery.proto

package discovery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryWorkerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWorkerStatusRequest) Reset() {
	*x = QueryWorkerStatusRequest{}
	mi := &file_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWorkerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWorkerStatusRequest) ProtoMessage() {}

func (x *QueryWorkerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWorkerStatusRequest.ProtoReflect.Descriptor instead.
func (*QueryWorkerStatusRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{0}
}

type QueryWorkerStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeName         string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`                            // Name of the worker node (e.g., hostname)
	AvailableCores   uint32                 `protobuf:"varint,2,opt,name=available_cores,json=availableCores,proto3" json:"available_cores,omitempty"`         // Number of CPU cores available to the worker
	TotalMemoryBytes uint64                 `protobuf:"varint,3,opt,name=total_memory_bytes,json=totalMemoryBytes,proto3" json:"total_memory_bytes,omitempty"` // Total physical memory in bytes
	FreeMemoryBytes  uint64                 `protobuf:"varint,4,opt,name=free_memory_bytes,json=freeMemoryBytes,proto3" json:"free_memory_bytes,omitempty"`    // Available physical memory in bytes
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryWorkerStatusResponse) Reset() {
	*x = QueryWorkerStatusResponse{}
	mi := &file_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWorkerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWorkerStatusResponse) ProtoMessage() {}

func (x *QueryWorkerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWorkerStatusResponse.ProtoReflect.Descriptor instead.
func (*QueryWorkerStatusResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *QueryWorkerStatusResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *QueryWorkerStatusResponse) GetAvailableCores() uint32 {
	if x != nil {
		return x.AvailableCores
	}
	return 0
}

func (x *QueryWorkerStatusResponse) GetTotalMemoryBytes() uint64 {
	if x != nil {
		return x.TotalMemoryBytes
	}
	return 0
}

func (x *QueryWorkerStatusResponse) GetFreeMemoryBytes() uint64 {
	if x != nil {
		return x.FreeMemoryBytes
	}
	return 0
}

var File_discovery_proto protoreflect.FileDescriptor

const file_discovery_proto_rawDesc = "" +
	"\n" +
	"\x0fdiscovery.proto\x12\tdiscovery\"\x1a\n" +
	"\x18QueryWorkerStatusRequest\"\xbb\x01\n" +
	"\x19QueryWorkerStatusResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12'\n" +
	"\x0favailable_cores\x18\x02 \x01(\rR\x0eavailableCores\x12,\n" +
	"\x12total_memory_bytes\x18\x03 \x01(\x04R\x10totalMemoryBytes\x12*\n" +
	"\x11free_memory_bytes\x18\x04 \x01(\x04R\x0ffreeMemoryBytes2x\n" +
	"\x16WorkerDiscoveryService\x12^\n" +
	"\x11QueryWorkerStatus\x12#.discovery.QueryWorkerStatusRequest\x1a$.discovery.QueryWorkerStatusResponseB>Z<github.com/flynn-nrg/izpi/internal/proto/discovery;discoveryb\x06proto3"

var (
	file_discovery_proto_rawDescOnce sync.Once
	file_discovery_proto_rawDescData []byte
)

func file_discovery_proto_rawDescGZIP() []byte {
	file_discovery_proto_rawDescOnce.Do(func() {
		file_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)))
	})
	return file_discovery_proto_rawDescData
}

var file_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_discovery_proto_goTypes = []any{
	(*QueryWorkerStatusRequest)(nil),  // 0: discovery.QueryWorkerStatusRequest
	(*QueryWorkerStatusResponse)(nil), // 1: discovery.QueryWorkerStatusResponse
}
var file_discovery_proto_depIdxs = []int32{
	0, // 0: discovery.WorkerDiscoveryService.QueryWorkerStatus:input_type -> discovery.QueryWorkerStatusRequest
	1, // 1: discovery.WorkerDiscoveryService.QueryWorkerStatus:output_type -> discovery.QueryWorkerStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_discovery_proto_init() }
func file_discovery_proto_init() {
	if File_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discovery_proto_goTypes,
		DependencyIndexes: file_discovery_proto_depIdxs,
		MessageInfos:      file_discovery_proto_msgTypes,
	}.Build()
	File_discovery_proto = out.File
	file_discovery_proto_goTypes = nil
	file_discovery_proto_depIdxs = nil
}
