// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: transport.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextureType int32

const (
	TextureType_TEXTURE_TYPE_UNSPECIFIED TextureType = 0
	TextureType_CONSTANT                 TextureType = 1
	TextureType_CHECKER                  TextureType = 2
	TextureType_IMAGE                    TextureType = 3
	TextureType_NOISE                    TextureType = 4
)

// Enum value maps for TextureType.
var (
	TextureType_name = map[int32]string{
		0: "TEXTURE_TYPE_UNSPECIFIED",
		1: "CONSTANT",
		2: "CHECKER",
		3: "IMAGE",
		4: "NOISE",
	}
	TextureType_value = map[string]int32{
		"TEXTURE_TYPE_UNSPECIFIED": 0,
		"CONSTANT":                 1,
		"CHECKER":                  2,
		"IMAGE":                    3,
		"NOISE":                    4,
	}
)

func (x TextureType) Enum() *TextureType {
	p := new(TextureType)
	*p = x
	return p
}

func (x TextureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextureType) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_proto_enumTypes[0].Descriptor()
}

func (TextureType) Type() protoreflect.EnumType {
	return &file_transport_proto_enumTypes[0]
}

func (x TextureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextureType.Descriptor instead.
func (TextureType) EnumDescriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{0}
}

type MaterialType int32

const (
	MaterialType_MATERIAL_TYPE_UNSPECIFIED MaterialType = 0
	MaterialType_DIELECTRIC                MaterialType = 1
	MaterialType_DIFFUSE_LIGHT             MaterialType = 2
	MaterialType_ISOTROPIC                 MaterialType = 3
	MaterialType_LAMBERT                   MaterialType = 4
	MaterialType_METAL                     MaterialType = 5
	MaterialType_PBR                       MaterialType = 6
)

// Enum value maps for MaterialType.
var (
	MaterialType_name = map[int32]string{
		0: "MATERIAL_TYPE_UNSPECIFIED",
		1: "DIELECTRIC",
		2: "DIFFUSE_LIGHT",
		3: "ISOTROPIC",
		4: "LAMBERT",
		5: "METAL",
		6: "PBR",
	}
	MaterialType_value = map[string]int32{
		"MATERIAL_TYPE_UNSPECIFIED": 0,
		"DIELECTRIC":                1,
		"DIFFUSE_LIGHT":             2,
		"ISOTROPIC":                 3,
		"LAMBERT":                   4,
		"METAL":                     5,
		"PBR":                       6,
	}
)

func (x MaterialType) Enum() *MaterialType {
	p := new(MaterialType)
	*p = x
	return p
}

func (x MaterialType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MaterialType) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_proto_enumTypes[1].Descriptor()
}

func (MaterialType) Type() protoreflect.EnumType {
	return &file_transport_proto_enumTypes[1]
}

func (x MaterialType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MaterialType.Descriptor instead.
func (MaterialType) EnumDescriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{1}
}

// Represents a 3D vector or point with float components.
type Vec3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec3) Reset() {
	*x = Vec3{}
	mi := &file_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec3) ProtoMessage() {}

func (x *Vec3) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec3.ProtoReflect.Descriptor instead.
func (*Vec3) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Vec3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vec3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// Represents a 2D vector or UV coordinate with float components.
type Vec2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	U             float32                `protobuf:"fixed32,1,opt,name=u,proto3" json:"u,omitempty"`
	V             float32                `protobuf:"fixed32,2,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	mi := &file_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{1}
}

func (x *Vec2) GetU() float32 {
	if x != nil {
		return x.U
	}
	return 0
}

func (x *Vec2) GetV() float32 {
	if x != nil {
		return x.V
	}
	return 0
}

// Represents the camera settings for the scene.
type Camera struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lookfrom      *Vec3                  `protobuf:"bytes,1,opt,name=lookfrom,proto3" json:"lookfrom,omitempty"`
	Lookat        *Vec3                  `protobuf:"bytes,2,opt,name=lookat,proto3" json:"lookat,omitempty"`
	Vup           *Vec3                  `protobuf:"bytes,3,opt,name=vup,proto3" json:"vup,omitempty"`
	Vfov          float32                `protobuf:"fixed32,4,opt,name=vfov,proto3" json:"vfov,omitempty"`
	Aspect        float32                `protobuf:"fixed32,5,opt,name=aspect,proto3" json:"aspect,omitempty"`
	Aperture      float32                `protobuf:"fixed32,6,opt,name=aperture,proto3" json:"aperture,omitempty"`
	Focusdist     float32                `protobuf:"fixed32,7,opt,name=focusdist,proto3" json:"focusdist,omitempty"`
	Time0         float32                `protobuf:"fixed32,8,opt,name=time0,proto3" json:"time0,omitempty"`
	Time1         float32                `protobuf:"fixed32,9,opt,name=time1,proto3" json:"time1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Camera) Reset() {
	*x = Camera{}
	mi := &file_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Camera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Camera) ProtoMessage() {}

func (x *Camera) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Camera.ProtoReflect.Descriptor instead.
func (*Camera) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{2}
}

func (x *Camera) GetLookfrom() *Vec3 {
	if x != nil {
		return x.Lookfrom
	}
	return nil
}

func (x *Camera) GetLookat() *Vec3 {
	if x != nil {
		return x.Lookat
	}
	return nil
}

func (x *Camera) GetVup() *Vec3 {
	if x != nil {
		return x.Vup
	}
	return nil
}

func (x *Camera) GetVfov() float32 {
	if x != nil {
		return x.Vfov
	}
	return 0
}

func (x *Camera) GetAspect() float32 {
	if x != nil {
		return x.Aspect
	}
	return 0
}

func (x *Camera) GetAperture() float32 {
	if x != nil {
		return x.Aperture
	}
	return 0
}

func (x *Camera) GetFocusdist() float32 {
	if x != nil {
		return x.Focusdist
	}
	return 0
}

func (x *Camera) GetTime0() float32 {
	if x != nil {
		return x.Time0
	}
	return 0
}

func (x *Camera) GetTime1() float32 {
	if x != nil {
		return x.Time1
	}
	return 0
}

// Represents different types of textures.
type Texture struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  TextureType            `protobuf:"varint,2,opt,name=type,proto3,enum=transport.TextureType" json:"type,omitempty"`
	// Types that are valid to be assigned to TextureProperties:
	//
	//	*Texture_Constant
	//	*Texture_Checker
	//	*Texture_Image
	//	*Texture_Noise
	TextureProperties isTexture_TextureProperties `protobuf_oneof:"texture_properties"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Texture) Reset() {
	*x = Texture{}
	mi := &file_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Texture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Texture) ProtoMessage() {}

func (x *Texture) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Texture.ProtoReflect.Descriptor instead.
func (*Texture) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{3}
}

func (x *Texture) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Texture) GetType() TextureType {
	if x != nil {
		return x.Type
	}
	return TextureType_TEXTURE_TYPE_UNSPECIFIED
}

func (x *Texture) GetTextureProperties() isTexture_TextureProperties {
	if x != nil {
		return x.TextureProperties
	}
	return nil
}

func (x *Texture) GetConstant() *ConstantTexture {
	if x != nil {
		if x, ok := x.TextureProperties.(*Texture_Constant); ok {
			return x.Constant
		}
	}
	return nil
}

func (x *Texture) GetChecker() *CheckerTexture {
	if x != nil {
		if x, ok := x.TextureProperties.(*Texture_Checker); ok {
			return x.Checker
		}
	}
	return nil
}

func (x *Texture) GetImage() *ImageTexture {
	if x != nil {
		if x, ok := x.TextureProperties.(*Texture_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *Texture) GetNoise() *NoiseTexture {
	if x != nil {
		if x, ok := x.TextureProperties.(*Texture_Noise); ok {
			return x.Noise
		}
	}
	return nil
}

type isTexture_TextureProperties interface {
	isTexture_TextureProperties()
}

type Texture_Constant struct {
	Constant *ConstantTexture `protobuf:"bytes,3,opt,name=constant,proto3,oneof"`
}

type Texture_Checker struct {
	Checker *CheckerTexture `protobuf:"bytes,4,opt,name=checker,proto3,oneof"`
}

type Texture_Image struct {
	Image *ImageTexture `protobuf:"bytes,5,opt,name=image,proto3,oneof"`
}

type Texture_Noise struct {
	Noise *NoiseTexture `protobuf:"bytes,6,opt,name=noise,proto3,oneof"`
}

func (*Texture_Constant) isTexture_TextureProperties() {}

func (*Texture_Checker) isTexture_TextureProperties() {}

func (*Texture_Image) isTexture_TextureProperties() {}

func (*Texture_Noise) isTexture_TextureProperties() {}

// Represents a constant color texture.
type ConstantTexture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Vec3                  `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConstantTexture) Reset() {
	*x = ConstantTexture{}
	mi := &file_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConstantTexture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstantTexture) ProtoMessage() {}

func (x *ConstantTexture) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstantTexture.ProtoReflect.Descriptor instead.
func (*ConstantTexture) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{4}
}

func (x *ConstantTexture) GetValue() *Vec3 {
	if x != nil {
		return x.Value
	}
	return nil
}

// Represents a checkerboard texture.
type CheckerTexture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Odd           *Texture               `protobuf:"bytes,1,opt,name=odd,proto3" json:"odd,omitempty"`
	Even          *Texture               `protobuf:"bytes,2,opt,name=even,proto3" json:"even,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckerTexture) Reset() {
	*x = CheckerTexture{}
	mi := &file_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckerTexture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckerTexture) ProtoMessage() {}

func (x *CheckerTexture) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckerTexture.ProtoReflect.Descriptor instead.
func (*CheckerTexture) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{5}
}

func (x *CheckerTexture) GetOdd() *Texture {
	if x != nil {
		return x.Odd
	}
	return nil
}

func (x *CheckerTexture) GetEven() *Texture {
	if x != nil {
		return x.Even
	}
	return nil
}

// Represents an image texture.
type ImageTexture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageTexture) Reset() {
	*x = ImageTexture{}
	mi := &file_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageTexture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageTexture) ProtoMessage() {}

func (x *ImageTexture) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageTexture.ProtoReflect.Descriptor instead.
func (*ImageTexture) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{6}
}

func (x *ImageTexture) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// Represents a noise texture.
type NoiseTexture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scale         float32                `protobuf:"fixed32,1,opt,name=scale,proto3" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoiseTexture) Reset() {
	*x = NoiseTexture{}
	mi := &file_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoiseTexture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoiseTexture) ProtoMessage() {}

func (x *NoiseTexture) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoiseTexture.ProtoReflect.Descriptor instead.
func (*NoiseTexture) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{7}
}

func (x *NoiseTexture) GetScale() float32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

// Represents different types of materials.
type Material struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Material name, used as key in the scene's materials map
	Type  MaterialType           `protobuf:"varint,2,opt,name=type,proto3,enum=transport.MaterialType" json:"type,omitempty"`
	// Types that are valid to be assigned to MaterialProperties:
	//
	//	*Material_Dielectric
	//	*Material_Diffuselight
	//	*Material_Isotropic
	//	*Material_Lambert
	//	*Material_Metal
	//	*Material_Pbr
	MaterialProperties isMaterial_MaterialProperties `protobuf_oneof:"material_properties"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Material) Reset() {
	*x = Material{}
	mi := &file_transport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Material) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Material) ProtoMessage() {}

func (x *Material) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Material.ProtoReflect.Descriptor instead.
func (*Material) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{8}
}

func (x *Material) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Material) GetType() MaterialType {
	if x != nil {
		return x.Type
	}
	return MaterialType_MATERIAL_TYPE_UNSPECIFIED
}

func (x *Material) GetMaterialProperties() isMaterial_MaterialProperties {
	if x != nil {
		return x.MaterialProperties
	}
	return nil
}

func (x *Material) GetDielectric() *DielectricMaterial {
	if x != nil {
		if x, ok := x.MaterialProperties.(*Material_Dielectric); ok {
			return x.Dielectric
		}
	}
	return nil
}

func (x *Material) GetDiffuselight() *DiffuseLightMaterial {
	if x != nil {
		if x, ok := x.MaterialProperties.(*Material_Diffuselight); ok {
			return x.Diffuselight
		}
	}
	return nil
}

func (x *Material) GetIsotropic() *IsotropicMaterial {
	if x != nil {
		if x, ok := x.MaterialProperties.(*Material_Isotropic); ok {
			return x.Isotropic
		}
	}
	return nil
}

func (x *Material) GetLambert() *LambertMaterial {
	if x != nil {
		if x, ok := x.MaterialProperties.(*Material_Lambert); ok {
			return x.Lambert
		}
	}
	return nil
}

func (x *Material) GetMetal() *MetalMaterial {
	if x != nil {
		if x, ok := x.MaterialProperties.(*Material_Metal); ok {
			return x.Metal
		}
	}
	return nil
}

func (x *Material) GetPbr() *PBRMaterial {
	if x != nil {
		if x, ok := x.MaterialProperties.(*Material_Pbr); ok {
			return x.Pbr
		}
	}
	return nil
}

type isMaterial_MaterialProperties interface {
	isMaterial_MaterialProperties()
}

type Material_Dielectric struct {
	Dielectric *DielectricMaterial `protobuf:"bytes,3,opt,name=dielectric,proto3,oneof"`
}

type Material_Diffuselight struct {
	Diffuselight *DiffuseLightMaterial `protobuf:"bytes,4,opt,name=diffuselight,proto3,oneof"`
}

type Material_Isotropic struct {
	Isotropic *IsotropicMaterial `protobuf:"bytes,5,opt,name=isotropic,proto3,oneof"`
}

type Material_Lambert struct {
	Lambert *LambertMaterial `protobuf:"bytes,6,opt,name=lambert,proto3,oneof"`
}

type Material_Metal struct {
	Metal *MetalMaterial `protobuf:"bytes,7,opt,name=metal,proto3,oneof"`
}

type Material_Pbr struct {
	Pbr *PBRMaterial `protobuf:"bytes,8,opt,name=pbr,proto3,oneof"`
}

func (*Material_Dielectric) isMaterial_MaterialProperties() {}

func (*Material_Diffuselight) isMaterial_MaterialProperties() {}

func (*Material_Isotropic) isMaterial_MaterialProperties() {}

func (*Material_Lambert) isMaterial_MaterialProperties() {}

func (*Material_Metal) isMaterial_MaterialProperties() {}

func (*Material_Pbr) isMaterial_MaterialProperties() {}

// Represents a Lambertian material.
type LambertMaterial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Albedo        *Texture               `protobuf:"bytes,1,opt,name=albedo,proto3" json:"albedo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LambertMaterial) Reset() {
	*x = LambertMaterial{}
	mi := &file_transport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LambertMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LambertMaterial) ProtoMessage() {}

func (x *LambertMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LambertMaterial.ProtoReflect.Descriptor instead.
func (*LambertMaterial) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{9}
}

func (x *LambertMaterial) GetAlbedo() *Texture {
	if x != nil {
		return x.Albedo
	}
	return nil
}

// Represents a Dielectric material.
type DielectricMaterial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refidx        float32                `protobuf:"fixed32,1,opt,name=refidx,proto3" json:"refidx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DielectricMaterial) Reset() {
	*x = DielectricMaterial{}
	mi := &file_transport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DielectricMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DielectricMaterial) ProtoMessage() {}

func (x *DielectricMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DielectricMaterial.ProtoReflect.Descriptor instead.
func (*DielectricMaterial) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{10}
}

func (x *DielectricMaterial) GetRefidx() float32 {
	if x != nil {
		return x.Refidx
	}
	return 0
}

// Represents a Diffuse Light material.
type DiffuseLightMaterial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emit          *Texture               `protobuf:"bytes,1,opt,name=emit,proto3" json:"emit,omitempty"` // Direct embedding of Texture
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffuseLightMaterial) Reset() {
	*x = DiffuseLightMaterial{}
	mi := &file_transport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffuseLightMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffuseLightMaterial) ProtoMessage() {}

func (x *DiffuseLightMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffuseLightMaterial.ProtoReflect.Descriptor instead.
func (*DiffuseLightMaterial) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{11}
}

func (x *DiffuseLightMaterial) GetEmit() *Texture {
	if x != nil {
		return x.Emit
	}
	return nil
}

// Represents an Isotropic material.
type IsotropicMaterial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Albedo        *Texture               `protobuf:"bytes,1,opt,name=albedo,proto3" json:"albedo,omitempty"` // Direct embedding of Texture
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsotropicMaterial) Reset() {
	*x = IsotropicMaterial{}
	mi := &file_transport_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsotropicMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsotropicMaterial) ProtoMessage() {}

func (x *IsotropicMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsotropicMaterial.ProtoReflect.Descriptor instead.
func (*IsotropicMaterial) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{12}
}

func (x *IsotropicMaterial) GetAlbedo() *Texture {
	if x != nil {
		return x.Albedo
	}
	return nil
}

// Represents a Metal material.
type MetalMaterial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Albedo        *Texture               `protobuf:"bytes,1,opt,name=albedo,proto3" json:"albedo,omitempty"` // Direct embedding of Texture
	Fuzz          float32                `protobuf:"fixed32,2,opt,name=fuzz,proto3" json:"fuzz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetalMaterial) Reset() {
	*x = MetalMaterial{}
	mi := &file_transport_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetalMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetalMaterial) ProtoMessage() {}

func (x *MetalMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetalMaterial.ProtoReflect.Descriptor instead.
func (*MetalMaterial) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{13}
}

func (x *MetalMaterial) GetAlbedo() *Texture {
	if x != nil {
		return x.Albedo
	}
	return nil
}

func (x *MetalMaterial) GetFuzz() float32 {
	if x != nil {
		return x.Fuzz
	}
	return 0
}

// Represents a Physically Based Rendering (PBR) material.
type PBRMaterial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Albedo        *Texture               `protobuf:"bytes,1,opt,name=albedo,proto3" json:"albedo,omitempty"`
	Roughness     *Texture               `protobuf:"bytes,2,opt,name=roughness,proto3" json:"roughness,omitempty"`
	Metalness     *Texture               `protobuf:"bytes,3,opt,name=metalness,proto3" json:"metalness,omitempty"`
	NormalMap     *Texture               `protobuf:"bytes,4,opt,name=normal_map,json=normalMap,proto3" json:"normal_map,omitempty"`
	Sss           *Texture               `protobuf:"bytes,5,opt,name=sss,proto3" json:"sss,omitempty"` // Subsurface Scattering
	SssRadius     float32                `protobuf:"fixed32,6,opt,name=sss_radius,json=sssRadius,proto3" json:"sss_radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBRMaterial) Reset() {
	*x = PBRMaterial{}
	mi := &file_transport_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBRMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBRMaterial) ProtoMessage() {}

func (x *PBRMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBRMaterial.ProtoReflect.Descriptor instead.
func (*PBRMaterial) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{14}
}

func (x *PBRMaterial) GetAlbedo() *Texture {
	if x != nil {
		return x.Albedo
	}
	return nil
}

func (x *PBRMaterial) GetRoughness() *Texture {
	if x != nil {
		return x.Roughness
	}
	return nil
}

func (x *PBRMaterial) GetMetalness() *Texture {
	if x != nil {
		return x.Metalness
	}
	return nil
}

func (x *PBRMaterial) GetNormalMap() *Texture {
	if x != nil {
		return x.NormalMap
	}
	return nil
}

func (x *PBRMaterial) GetSss() *Texture {
	if x != nil {
		return x.Sss
	}
	return nil
}

func (x *PBRMaterial) GetSssRadius() float32 {
	if x != nil {
		return x.SssRadius
	}
	return 0
}

// Represents a triangle object with per-vertex data.
type Triangle struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Vertex0 *Vec3                  `protobuf:"bytes,1,opt,name=vertex0,proto3" json:"vertex0,omitempty"`
	Vertex1 *Vec3                  `protobuf:"bytes,2,opt,name=vertex1,proto3" json:"vertex1,omitempty"`
	Vertex2 *Vec3                  `protobuf:"bytes,3,opt,name=vertex2,proto3" json:"vertex2,omitempty"`
	// UV coordinates for each vertex
	Uv0 *Vec2 `protobuf:"bytes,4,opt,name=uv0,proto3" json:"uv0,omitempty"`
	Uv1 *Vec2 `protobuf:"bytes,5,opt,name=uv1,proto3" json:"uv1,omitempty"`
	Uv2 *Vec2 `protobuf:"bytes,6,opt,name=uv2,proto3" json:"uv2,omitempty"`
	// Per-vertex normal vectors for smooth shading
	Normal0       *Vec3  `protobuf:"bytes,7,opt,name=normal0,proto3" json:"normal0,omitempty"`
	Normal1       *Vec3  `protobuf:"bytes,8,opt,name=normal1,proto3" json:"normal1,omitempty"`
	Normal2       *Vec3  `protobuf:"bytes,9,opt,name=normal2,proto3" json:"normal2,omitempty"`
	MaterialName  string `protobuf:"bytes,10,opt,name=material_name,json=materialName,proto3" json:"material_name,omitempty"` // Reference material by name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Triangle) Reset() {
	*x = Triangle{}
	mi := &file_transport_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Triangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Triangle) ProtoMessage() {}

func (x *Triangle) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Triangle.ProtoReflect.Descriptor instead.
func (*Triangle) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{15}
}

func (x *Triangle) GetVertex0() *Vec3 {
	if x != nil {
		return x.Vertex0
	}
	return nil
}

func (x *Triangle) GetVertex1() *Vec3 {
	if x != nil {
		return x.Vertex1
	}
	return nil
}

func (x *Triangle) GetVertex2() *Vec3 {
	if x != nil {
		return x.Vertex2
	}
	return nil
}

func (x *Triangle) GetUv0() *Vec2 {
	if x != nil {
		return x.Uv0
	}
	return nil
}

func (x *Triangle) GetUv1() *Vec2 {
	if x != nil {
		return x.Uv1
	}
	return nil
}

func (x *Triangle) GetUv2() *Vec2 {
	if x != nil {
		return x.Uv2
	}
	return nil
}

func (x *Triangle) GetNormal0() *Vec3 {
	if x != nil {
		return x.Normal0
	}
	return nil
}

func (x *Triangle) GetNormal1() *Vec3 {
	if x != nil {
		return x.Normal1
	}
	return nil
}

func (x *Triangle) GetNormal2() *Vec3 {
	if x != nil {
		return x.Normal2
	}
	return nil
}

func (x *Triangle) GetMaterialName() string {
	if x != nil {
		return x.MaterialName
	}
	return ""
}

// Represents a sphere object.
type Sphere struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Center        *Vec3                  `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	Radius        float32                `protobuf:"fixed32,2,opt,name=radius,proto3" json:"radius,omitempty"`
	MaterialName  string                 `protobuf:"bytes,3,opt,name=material_name,json=materialName,proto3" json:"material_name,omitempty"` // Reference material by name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sphere) Reset() {
	*x = Sphere{}
	mi := &file_transport_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sphere) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sphere) ProtoMessage() {}

func (x *Sphere) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sphere.ProtoReflect.Descriptor instead.
func (*Sphere) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{16}
}

func (x *Sphere) GetCenter() *Vec3 {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *Sphere) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *Sphere) GetMaterialName() string {
	if x != nil {
		return x.MaterialName
	}
	return ""
}

// Contains all the objects in the scene.
type SceneObjects struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Triangles     []*Triangle            `protobuf:"bytes,1,rep,name=triangles,proto3" json:"triangles,omitempty"`
	Spheres       []*Sphere              `protobuf:"bytes,2,rep,name=spheres,proto3" json:"spheres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneObjects) Reset() {
	*x = SceneObjects{}
	mi := &file_transport_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneObjects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneObjects) ProtoMessage() {}

func (x *SceneObjects) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneObjects.ProtoReflect.Descriptor instead.
func (*SceneObjects) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{17}
}

func (x *SceneObjects) GetTriangles() []*Triangle {
	if x != nil {
		return x.Triangles
	}
	return nil
}

func (x *SceneObjects) GetSpheres() []*Sphere {
	if x != nil {
		return x.Spheres
	}
	return nil
}

// The root message describing the entire scene.
type Scene struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Camera        *Camera                `protobuf:"bytes,3,opt,name=camera,proto3" json:"camera,omitempty"`
	Materials     map[string]*Material   `protobuf:"bytes,4,rep,name=materials,proto3" json:"materials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Objects       *SceneObjects          `protobuf:"bytes,5,opt,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scene) Reset() {
	*x = Scene{}
	mi := &file_transport_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scene) ProtoMessage() {}

func (x *Scene) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scene.ProtoReflect.Descriptor instead.
func (*Scene) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{18}
}

func (x *Scene) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scene) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Scene) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

func (x *Scene) GetMaterials() map[string]*Material {
	if x != nil {
		return x.Materials
	}
	return nil
}

func (x *Scene) GetObjects() *SceneObjects {
	if x != nil {
		return x.Objects
	}
	return nil
}

// Request to retrieve a specific scene.
type GetSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneName     string                 `protobuf:"bytes,1,opt,name=scene_name,json=sceneName,proto3" json:"scene_name,omitempty"` // Identifier for the scene to retrieve.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSceneRequest) Reset() {
	*x = GetSceneRequest{}
	mi := &file_transport_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSceneRequest) ProtoMessage() {}

func (x *GetSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSceneRequest.ProtoReflect.Descriptor instead.
func (*GetSceneRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{19}
}

func (x *GetSceneRequest) GetSceneName() string {
	if x != nil {
		return x.SceneName
	}
	return ""
}

// Request to stream the content of a texture file.
type StreamTextureFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                     // The path/name of the texture file to stream.
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`                        // The starting byte offset in the file to begin streaming from.
	ChunkSize     uint32                 `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"` // The maximum size of each chunk to stream in bytes.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTextureFileRequest) Reset() {
	*x = StreamTextureFileRequest{}
	mi := &file_transport_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTextureFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTextureFileRequest) ProtoMessage() {}

func (x *StreamTextureFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTextureFileRequest.ProtoReflect.Descriptor instead.
func (*StreamTextureFileRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{20}
}

func (x *StreamTextureFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *StreamTextureFileRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StreamTextureFileRequest) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

// A chunk of binary data for a streamed texture file.
type StreamTextureFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"` // A segment of the texture file's binary data.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTextureFileResponse) Reset() {
	*x = StreamTextureFileResponse{}
	mi := &file_transport_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTextureFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTextureFileResponse) ProtoMessage() {}

func (x *StreamTextureFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTextureFileResponse.ProtoReflect.Descriptor instead.
func (*StreamTextureFileResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{21}
}

func (x *StreamTextureFileResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_transport_proto protoreflect.FileDescriptor

const file_transport_proto_rawDesc = "" +
	"\n" +
	"\x0ftransport.proto\x12\ttransport\"0\n" +
	"\x04Vec3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"\"\n" +
	"\x04Vec2\x12\f\n" +
	"\x01u\x18\x01 \x01(\x02R\x01u\x12\f\n" +
	"\x01v\x18\x02 \x01(\x02R\x01v\"\x93\x02\n" +
	"\x06Camera\x12+\n" +
	"\blookfrom\x18\x01 \x01(\v2\x0f.transport.Vec3R\blookfrom\x12'\n" +
	"\x06lookat\x18\x02 \x01(\v2\x0f.transport.Vec3R\x06lookat\x12!\n" +
	"\x03vup\x18\x03 \x01(\v2\x0f.transport.Vec3R\x03vup\x12\x12\n" +
	"\x04vfov\x18\x04 \x01(\x02R\x04vfov\x12\x16\n" +
	"\x06aspect\x18\x05 \x01(\x02R\x06aspect\x12\x1a\n" +
	"\baperture\x18\x06 \x01(\x02R\baperture\x12\x1c\n" +
	"\tfocusdist\x18\a \x01(\x02R\tfocusdist\x12\x14\n" +
	"\x05time0\x18\b \x01(\x02R\x05time0\x12\x14\n" +
	"\x05time1\x18\t \x01(\x02R\x05time1\"\xb2\x02\n" +
	"\aTexture\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.transport.TextureTypeR\x04type\x128\n" +
	"\bconstant\x18\x03 \x01(\v2\x1a.transport.ConstantTextureH\x00R\bconstant\x125\n" +
	"\achecker\x18\x04 \x01(\v2\x19.transport.CheckerTextureH\x00R\achecker\x12/\n" +
	"\x05image\x18\x05 \x01(\v2\x17.transport.ImageTextureH\x00R\x05image\x12/\n" +
	"\x05noise\x18\x06 \x01(\v2\x17.transport.NoiseTextureH\x00R\x05noiseB\x14\n" +
	"\x12texture_properties\"8\n" +
	"\x0fConstantTexture\x12%\n" +
	"\x05value\x18\x01 \x01(\v2\x0f.transport.Vec3R\x05value\"^\n" +
	"\x0eCheckerTexture\x12$\n" +
	"\x03odd\x18\x01 \x01(\v2\x12.transport.TextureR\x03odd\x12&\n" +
	"\x04even\x18\x02 \x01(\v2\x12.transport.TextureR\x04even\"*\n" +
	"\fImageTexture\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"$\n" +
	"\fNoiseTexture\x12\x14\n" +
	"\x05scale\x18\x01 \x01(\x02R\x05scale\"\xbe\x03\n" +
	"\bMaterial\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.transport.MaterialTypeR\x04type\x12?\n" +
	"\n" +
	"dielectric\x18\x03 \x01(\v2\x1d.transport.DielectricMaterialH\x00R\n" +
	"dielectric\x12E\n" +
	"\fdiffuselight\x18\x04 \x01(\v2\x1f.transport.DiffuseLightMaterialH\x00R\fdiffuselight\x12<\n" +
	"\tisotropic\x18\x05 \x01(\v2\x1c.transport.IsotropicMaterialH\x00R\tisotropic\x126\n" +
	"\alambert\x18\x06 \x01(\v2\x1a.transport.LambertMaterialH\x00R\alambert\x120\n" +
	"\x05metal\x18\a \x01(\v2\x18.transport.MetalMaterialH\x00R\x05metal\x12*\n" +
	"\x03pbr\x18\b \x01(\v2\x16.transport.PBRMaterialH\x00R\x03pbrB\x15\n" +
	"\x13material_properties\"=\n" +
	"\x0fLambertMaterial\x12*\n" +
	"\x06albedo\x18\x01 \x01(\v2\x12.transport.TextureR\x06albedo\",\n" +
	"\x12DielectricMaterial\x12\x16\n" +
	"\x06refidx\x18\x01 \x01(\x02R\x06refidx\">\n" +
	"\x14DiffuseLightMaterial\x12&\n" +
	"\x04emit\x18\x01 \x01(\v2\x12.transport.TextureR\x04emit\"?\n" +
	"\x11IsotropicMaterial\x12*\n" +
	"\x06albedo\x18\x01 \x01(\v2\x12.transport.TextureR\x06albedo\"O\n" +
	"\rMetalMaterial\x12*\n" +
	"\x06albedo\x18\x01 \x01(\v2\x12.transport.TextureR\x06albedo\x12\x12\n" +
	"\x04fuzz\x18\x02 \x01(\x02R\x04fuzz\"\x95\x02\n" +
	"\vPBRMaterial\x12*\n" +
	"\x06albedo\x18\x01 \x01(\v2\x12.transport.TextureR\x06albedo\x120\n" +
	"\troughness\x18\x02 \x01(\v2\x12.transport.TextureR\troughness\x120\n" +
	"\tmetalness\x18\x03 \x01(\v2\x12.transport.TextureR\tmetalness\x121\n" +
	"\n" +
	"normal_map\x18\x04 \x01(\v2\x12.transport.TextureR\tnormalMap\x12$\n" +
	"\x03sss\x18\x05 \x01(\v2\x12.transport.TextureR\x03sss\x12\x1d\n" +
	"\n" +
	"sss_radius\x18\x06 \x01(\x02R\tsssRadius\"\x9a\x03\n" +
	"\bTriangle\x12)\n" +
	"\avertex0\x18\x01 \x01(\v2\x0f.transport.Vec3R\avertex0\x12)\n" +
	"\avertex1\x18\x02 \x01(\v2\x0f.transport.Vec3R\avertex1\x12)\n" +
	"\avertex2\x18\x03 \x01(\v2\x0f.transport.Vec3R\avertex2\x12!\n" +
	"\x03uv0\x18\x04 \x01(\v2\x0f.transport.Vec2R\x03uv0\x12!\n" +
	"\x03uv1\x18\x05 \x01(\v2\x0f.transport.Vec2R\x03uv1\x12!\n" +
	"\x03uv2\x18\x06 \x01(\v2\x0f.transport.Vec2R\x03uv2\x12)\n" +
	"\anormal0\x18\a \x01(\v2\x0f.transport.Vec3R\anormal0\x12)\n" +
	"\anormal1\x18\b \x01(\v2\x0f.transport.Vec3R\anormal1\x12)\n" +
	"\anormal2\x18\t \x01(\v2\x0f.transport.Vec3R\anormal2\x12#\n" +
	"\rmaterial_name\x18\n" +
	" \x01(\tR\fmaterialName\"n\n" +
	"\x06Sphere\x12'\n" +
	"\x06center\x18\x01 \x01(\v2\x0f.transport.Vec3R\x06center\x12\x16\n" +
	"\x06radius\x18\x02 \x01(\x02R\x06radius\x12#\n" +
	"\rmaterial_name\x18\x03 \x01(\tR\fmaterialName\"n\n" +
	"\fSceneObjects\x121\n" +
	"\ttriangles\x18\x01 \x03(\v2\x13.transport.TriangleR\ttriangles\x12+\n" +
	"\aspheres\x18\x02 \x03(\v2\x11.transport.SphereR\aspheres\"\xa5\x02\n" +
	"\x05Scene\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x06camera\x18\x03 \x01(\v2\x11.transport.CameraR\x06camera\x12=\n" +
	"\tmaterials\x18\x04 \x03(\v2\x1f.transport.Scene.MaterialsEntryR\tmaterials\x121\n" +
	"\aobjects\x18\x05 \x01(\v2\x17.transport.SceneObjectsR\aobjects\x1aQ\n" +
	"\x0eMaterialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.transport.MaterialR\x05value:\x028\x01\"0\n" +
	"\x0fGetSceneRequest\x12\x1d\n" +
	"\n" +
	"scene_name\x18\x01 \x01(\tR\tsceneName\"m\n" +
	"\x18StreamTextureFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\rR\tchunkSize\"1\n" +
	"\x19StreamTextureFileResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk*\\\n" +
	"\vTextureType\x12\x1c\n" +
	"\x18TEXTURE_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCONSTANT\x10\x01\x12\v\n" +
	"\aCHECKER\x10\x02\x12\t\n" +
	"\x05IMAGE\x10\x03\x12\t\n" +
	"\x05NOISE\x10\x04*\x80\x01\n" +
	"\fMaterialType\x12\x1d\n" +
	"\x19MATERIAL_TYPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"DIELECTRIC\x10\x01\x12\x11\n" +
	"\rDIFFUSE_LIGHT\x10\x02\x12\r\n" +
	"\tISOTROPIC\x10\x03\x12\v\n" +
	"\aLAMBERT\x10\x04\x12\t\n" +
	"\x05METAL\x10\x05\x12\a\n" +
	"\x03PBR\x10\x062\xb3\x01\n" +
	"\x15SceneTransportService\x128\n" +
	"\bGetScene\x12\x1a.transport.GetSceneRequest\x1a\x10.transport.Scene\x12`\n" +
	"\x11StreamTextureFile\x12#.transport.StreamTextureFileRequest\x1a$.transport.StreamTextureFileResponse0\x01B>Z<github.com/flynn-nrg/izpi/internal/proto/transport;transportb\x06proto3"

var (
	file_transport_proto_rawDescOnce sync.Once
	file_transport_proto_rawDescData []byte
)

func file_transport_proto_rawDescGZIP() []byte {
	file_transport_proto_rawDescOnce.Do(func() {
		file_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_proto_rawDesc), len(file_transport_proto_rawDesc)))
	})
	return file_transport_proto_rawDescData
}

var file_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_transport_proto_goTypes = []any{
	(TextureType)(0),                  // 0: transport.TextureType
	(MaterialType)(0),                 // 1: transport.MaterialType
	(*Vec3)(nil),                      // 2: transport.Vec3
	(*Vec2)(nil),                      // 3: transport.Vec2
	(*Camera)(nil),                    // 4: transport.Camera
	(*Texture)(nil),                   // 5: transport.Texture
	(*ConstantTexture)(nil),           // 6: transport.ConstantTexture
	(*CheckerTexture)(nil),            // 7: transport.CheckerTexture
	(*ImageTexture)(nil),              // 8: transport.ImageTexture
	(*NoiseTexture)(nil),              // 9: transport.NoiseTexture
	(*Material)(nil),                  // 10: transport.Material
	(*LambertMaterial)(nil),           // 11: transport.LambertMaterial
	(*DielectricMaterial)(nil),        // 12: transport.DielectricMaterial
	(*DiffuseLightMaterial)(nil),      // 13: transport.DiffuseLightMaterial
	(*IsotropicMaterial)(nil),         // 14: transport.IsotropicMaterial
	(*MetalMaterial)(nil),             // 15: transport.MetalMaterial
	(*PBRMaterial)(nil),               // 16: transport.PBRMaterial
	(*Triangle)(nil),                  // 17: transport.Triangle
	(*Sphere)(nil),                    // 18: transport.Sphere
	(*SceneObjects)(nil),              // 19: transport.SceneObjects
	(*Scene)(nil),                     // 20: transport.Scene
	(*GetSceneRequest)(nil),           // 21: transport.GetSceneRequest
	(*StreamTextureFileRequest)(nil),  // 22: transport.StreamTextureFileRequest
	(*StreamTextureFileResponse)(nil), // 23: transport.StreamTextureFileResponse
	nil,                               // 24: transport.Scene.MaterialsEntry
}
var file_transport_proto_depIdxs = []int32{
	2,  // 0: transport.Camera.lookfrom:type_name -> transport.Vec3
	2,  // 1: transport.Camera.lookat:type_name -> transport.Vec3
	2,  // 2: transport.Camera.vup:type_name -> transport.Vec3
	0,  // 3: transport.Texture.type:type_name -> transport.TextureType
	6,  // 4: transport.Texture.constant:type_name -> transport.ConstantTexture
	7,  // 5: transport.Texture.checker:type_name -> transport.CheckerTexture
	8,  // 6: transport.Texture.image:type_name -> transport.ImageTexture
	9,  // 7: transport.Texture.noise:type_name -> transport.NoiseTexture
	2,  // 8: transport.ConstantTexture.value:type_name -> transport.Vec3
	5,  // 9: transport.CheckerTexture.odd:type_name -> transport.Texture
	5,  // 10: transport.CheckerTexture.even:type_name -> transport.Texture
	1,  // 11: transport.Material.type:type_name -> transport.MaterialType
	12, // 12: transport.Material.dielectric:type_name -> transport.DielectricMaterial
	13, // 13: transport.Material.diffuselight:type_name -> transport.DiffuseLightMaterial
	14, // 14: transport.Material.isotropic:type_name -> transport.IsotropicMaterial
	11, // 15: transport.Material.lambert:type_name -> transport.LambertMaterial
	15, // 16: transport.Material.metal:type_name -> transport.MetalMaterial
	16, // 17: transport.Material.pbr:type_name -> transport.PBRMaterial
	5,  // 18: transport.LambertMaterial.albedo:type_name -> transport.Texture
	5,  // 19: transport.DiffuseLightMaterial.emit:type_name -> transport.Texture
	5,  // 20: transport.IsotropicMaterial.albedo:type_name -> transport.Texture
	5,  // 21: transport.MetalMaterial.albedo:type_name -> transport.Texture
	5,  // 22: transport.PBRMaterial.albedo:type_name -> transport.Texture
	5,  // 23: transport.PBRMaterial.roughness:type_name -> transport.Texture
	5,  // 24: transport.PBRMaterial.metalness:type_name -> transport.Texture
	5,  // 25: transport.PBRMaterial.normal_map:type_name -> transport.Texture
	5,  // 26: transport.PBRMaterial.sss:type_name -> transport.Texture
	2,  // 27: transport.Triangle.vertex0:type_name -> transport.Vec3
	2,  // 28: transport.Triangle.vertex1:type_name -> transport.Vec3
	2,  // 29: transport.Triangle.vertex2:type_name -> transport.Vec3
	3,  // 30: transport.Triangle.uv0:type_name -> transport.Vec2
	3,  // 31: transport.Triangle.uv1:type_name -> transport.Vec2
	3,  // 32: transport.Triangle.uv2:type_name -> transport.Vec2
	2,  // 33: transport.Triangle.normal0:type_name -> transport.Vec3
	2,  // 34: transport.Triangle.normal1:type_name -> transport.Vec3
	2,  // 35: transport.Triangle.normal2:type_name -> transport.Vec3
	2,  // 36: transport.Sphere.center:type_name -> transport.Vec3
	17, // 37: transport.SceneObjects.triangles:type_name -> transport.Triangle
	18, // 38: transport.SceneObjects.spheres:type_name -> transport.Sphere
	4,  // 39: transport.Scene.camera:type_name -> transport.Camera
	24, // 40: transport.Scene.materials:type_name -> transport.Scene.MaterialsEntry
	19, // 41: transport.Scene.objects:type_name -> transport.SceneObjects
	10, // 42: transport.Scene.MaterialsEntry.value:type_name -> transport.Material
	21, // 43: transport.SceneTransportService.GetScene:input_type -> transport.GetSceneRequest
	22, // 44: transport.SceneTransportService.StreamTextureFile:input_type -> transport.StreamTextureFileRequest
	20, // 45: transport.SceneTransportService.GetScene:output_type -> transport.Scene
	23, // 46: transport.SceneTransportService.StreamTextureFile:output_type -> transport.StreamTextureFileResponse
	45, // [45:47] is the sub-list for method output_type
	43, // [43:45] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_transport_proto_init() }
func file_transport_proto_init() {
	if File_transport_proto != nil {
		return
	}
	file_transport_proto_msgTypes[3].OneofWrappers = []any{
		(*Texture_Constant)(nil),
		(*Texture_Checker)(nil),
		(*Texture_Image)(nil),
		(*Texture_Noise)(nil),
	}
	file_transport_proto_msgTypes[8].OneofWrappers = []any{
		(*Material_Dielectric)(nil),
		(*Material_Diffuselight)(nil),
		(*Material_Isotropic)(nil),
		(*Material_Lambert)(nil),
		(*Material_Metal)(nil),
		(*Material_Pbr)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_proto_rawDesc), len(file_transport_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_proto_goTypes,
		DependencyIndexes: file_transport_proto_depIdxs,
		EnumInfos:         file_transport_proto_enumTypes,
		MessageInfos:      file_transport_proto_msgTypes,
	}.Build()
	File_transport_proto = out.File
	file_transport_proto_goTypes = nil
	file_transport_proto_depIdxs = nil
}
